### ISSUE TITLE
Issue running local Haiven with ollama

### ISSUE THREAD

**Issue by karthik-krishnan** [tw-haiven/haiven#180]
Looks like the application is looking for api_key even when running in the local mode with ollama.  App seems to be looking for the api key credentials, which should not be the case.

openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
    +-----------

My .env is 
# SOURCE FOR PROMPTS AND KNOWLEDGE
# Check the documentation for the expected structure of the folder
TEAM_CONTENT_PATH=../demo-knowledge-pack
# Name of the domain to enable (subfolder name in the content path)
DOMAIN_NAME=team_demo

AUTH_SWITCHED_OFF=true

# ENABLED MODELS
ENABLED_PROVIDERS=ollama
ENABLED_EMBEDDINGS_MODEL=ollama
ENABLED_VISION_MODEL=llava:7b

OLLAMA_BASE_URL=http://localhost:11434

**Comment by karthik-krishnan** [comment]
@birgitta410 - noticed that JSONChat class is instantiating llm_config with azure_llm, instead of using the configured llm_config from the enviornment, which could be the issue?

**Comment by AshpatTW** [comment]
@karthik-krishnan Just tried running the application with Ollama (llama3) did not see the error. Can you elaborate a bit more, like which tab or screen you were using when you saw this error. Or is it coming up at startup ?

**Comment by karthik-krishnan** [comment]
Hey Ashish,

Thanks for reaching out.  I was trying to use the Requirements breakdown function, see screenshot below

***@***.***

Best regards,

Karthik Krishnan
https://karthiks.in
https://ddd-practitioners.com



From: Ashish Patil ***@***.***>
Date: Wednesday, June 26, 2024 at 2:22 AM
To: tw-haiven/haiven ***@***.***>
Cc: karthik-krishnan ***@***.***>, Mention ***@***.***>
Subject: Re: [tw-haiven/haiven] Issue running local Haiven with ollama (Issue #180)

@karthik-krishnan<https://github.com/karthik-krishnan> Just tried running the application with Ollama (llama3) did not see the error. Can you elaborate a bit more, like which tab or screen you were using when you saw this error. Or is it coming up at startup ?
